from aiida_lammps.data.pot_plugins.base_plugin import PotentialAbstract


class EAM(PotentialAbstract):
    """Class for creation of EAM potential inputs."""

    def get_potential_file_content(self, data):
        # potential_file = (
        #     "# Potential file generated by aiida plugin "
        #     "(please check citation in the orignal file)\n"
        # )
        potential_file = ""
        for line in data["file_contents"]:
            potential_file += "{}".format(line)

        return potential_file

    def get_input_potential_lines(
        self, data, kind_elements=None, potential_filename="potential.pot"
    ):

        lammps_input_text = "pair_style      eam/{}\n".format(data["type"])
        lammps_input_text += "pair_coeff      * * {} {}\n".format(
            potential_filename, " ".join(kind_elements)
        )

        return lammps_input_text

    @property
    def atom_style(self):
        return "atomic"

    @property
    def default_units(self):
        return "metal"
