

def generate_LAMMPS_potential(data):
    potential_file = '# Potential file generated by aiida plugin (please check citation in the orignal file)\n'
    for key, value in data.iteritems():
        potential_file += '{}    {}\n'.format(key, value)

    return potential_file


def get_input_potential_lines(data, names=None, potential_filename='potential.pot'):

    lammps_input_text = 'pair_style      tersoff\n'
    lammps_input_text += 'pair_coeff      * * {} {}\n'.format(potential_filename, ' '.join(names))

    return lammps_input_text